### ISSUE TITLE
3D : 3D Sign

### ISSUE THREAD

**Issue by miw1234** [Prakkkmak/Space-Station-Lambda#190]
3d sign instead of quad mesh
![unknown](https://user-images.githubusercontent.com/49024001/127120115-75b1c37b-d20e-4a27-af98-b42365678b22.png)

**Comment by Prakkkmak** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Sign](https://trello.com/c/t616DZ5c/10-sign)
